<!DOCTYPE div PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/dojo/1.7/dijit/themes/claro/claro.css" />
<?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>

<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojo/dojo.js" djConfig="parseOnLoad: true, isDebug: true"></script>
<script type="text/javascript">
dojo.require("dijit.dijit");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.data.ItemFileReadStore");
dojo.require("dijit.tree.ForestStoreModel");

/*
dojo.require("dijit.Tree");
dojo.require("dojo.data.ItemFileReadStore");
*/
dojo.addOnLoad(function() {
	
});
function dojoRequire(items){
	
}
function require_dojo_items(items){
	for(var id in items){
		try{
			dojo.require(items[id]);
		}catch(exception){
			alert(exception);
		}
	}
}
</script>
</head>
<body class="claro">
<div style="width: 100%; height: 700px; ">
    <div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 100%;">
        <div dojoType="dijit.layout.ContentPane" region="top" splitter="true" style="height:20px;">
            欢迎来到后台
            <div class="r"><a href="#" >退出</a></div>
        </div>
        <div dojoType="dijit.layout.ContentPane" region="top" splitter="true" style="height:30px;">
            <?php echo $this->layout()->menubar; ?>
        </div>
        <div dojoType="dijit.layout.ContentPane" region="left" style="width: 210px;" splitter="true">
            
        </div>
        <div dojoType="dijit.layout.ContentPane" region="center" splitter="true">
        <div id="workFrame"></div>
        	
        </div>
        <div dojoType="dijit.layout.ContentPane" region="bottom" splitter="true" style="height:30px;">
             
         </div>
     </div>
</div>
</body>
</html>